/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/FallingLeavesBackground`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/feed/api`; params?: Router.UnknownInputParams; } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/feed/types`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/Badges`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/BottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/CommentsModal`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/Rankings`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/ReactionsBar`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/FallingLeavesBackground`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/api`; params?: Router.UnknownOutputParams; } | { pathname: `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/types`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/Badges`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/BottomNav`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/CommentsModal`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/ProfileHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/Rankings`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/components/ReactionsBar`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/FallingLeavesBackground${`?${string}` | `#${string}` | ''}` | `/auth/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/auth/login.styles${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/feed/api${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `/feed/types${`?${string}` | `#${string}` | ''}` | `/feed/components/Badges${`?${string}` | `#${string}` | ''}` | `/feed/components/BottomNav${`?${string}` | `#${string}` | ''}` | `/feed/components/CommentsModal${`?${string}` | `#${string}` | ''}` | `/feed/components/ProfileHeader${`?${string}` | `#${string}` | ''}` | `/feed/components/Rankings${`?${string}` | `#${string}` | ''}` | `/feed/components/ReactionsBar${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/FallingLeavesBackground`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login.styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/feed/api`; params?: Router.UnknownInputParams; } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/feed/types`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/Badges`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/BottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/CommentsModal`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/Rankings`; params?: Router.UnknownInputParams; } | { pathname: `/feed/components/ReactionsBar`; params?: Router.UnknownInputParams; };
    }
  }
}
